### ISSUE TITLE
The result area is not responsive

### ISSUE THREAD

**Issue by nctl144** [nctl144/spot-on#5]
If you take a look at the homepage, you will see that there are 4 columns of products. However, if you resize the browser windows, you will see that the layout collapses. Therefore, you will need to go inside the template and make the layout responsive somehow. [Here](https://getmdl.io/components/index.html#layout-section) is the resource that you might find useful. Scroll down and see the **Grid** section :) @JohnAsare

**Comment by JohnAsare** [comment]
Alright bro. I have created the page that introduce our project. I will check [your link ](https://getmdl.io/components/index.html#layout-section) too to fix the issue

**Comment by nctl144** [comment]
yeah make sure to make another Pull Request from a new branch for this issue @JohnAsare .
Before you work on it, check out to the master branch and create a new branch.
