### ISSUE TITLE
Fix the look for the tags in the input

### ISSUE THREAD

**Issue by nctl144** [nctl144/spot-on#7]
Right now if you go to http://127.0.0.1:8000/result/ and type something in the search box then press enter, you will see the tags appear like this: 
<img width="161" alt="screen shot 2018-04-13 at 7 57 09 pm" src="https://user-images.githubusercontent.com/17996166/38761923-e5dbf822-3f54-11e8-8fb0-2eb47235caaa.png">
However, I want them to look like this:
<img width="187" alt="screen shot 2018-04-13 at 7 57 55 pm" src="https://user-images.githubusercontent.com/17996166/38761934-fa273c2e-3f54-11e8-89c5-3f12717a25bc.png">

Go into main.css and add some properties that can change the look of these tags. you might find this part of Github page useful by inspecting with the browser developer tool. It might give you some idea of how to do this!
<img width="953" alt="screen shot 2018-04-13 at 7 58 40 pm" src="https://user-images.githubusercontent.com/17996166/38761963-2ea3d30e-3f55-11e8-8218-0b1b7872c854.png">
@JohnAsare

**Comment by JohnAsare** [comment]
I have looked into it and you will have to explain more of this bug to me. For the meantime, I am still doing research on it
